// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/alejandrobyrne/website/internal/projects_store"
	"github.com/alejandrobyrne/website/internal/substack"
	"github.com/alejandrobyrne/website/views/components"
	"github.com/alejandrobyrne/website/views/layout"
)

type HomeData struct {
	RecentPosts      []substack.Post
	FeaturedProjects []projects_store.Project
}

func Index(data HomeData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <section class=\"mb-12 py-10 border-b-2 border-black\"><h1 class=\"text-3xl font-bold mb-6 uppercase tracking-widest\">Alejandro Byrne</h1><div class=\"text-lg max-w-2xl leading-relaxed space-y-4\"><p>CS Senior. Texas based.</p><p>Building high-performance systems with <strong>Go, Azure, and Post-React</strong> technologies. </p></div><div class=\"mt-8 flex gap-4\"><a href=\"/projects\" class=\"border-2 border-black px-6 py-2 font-bold hover:bg-black hover:text-white transition-colors duration-0 uppercase text-sm\">View My Work</a></div></section> <div class=\"mb-16 border-b-2 border-black pb-8\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Slideshow([]components.Slide{
				{Src: "donkeys.jpg", Caption: "Grazing donkeys in the highlands of Northern Peru."},
				{Src: "tinco_peru.jpg", Caption: "Village of Tinco, Peru."},
				{Src: "colorado_bend_state_park.jpg", Caption: "Hiking trails at Colorado Bend State Park."},
				{Src: "bike_in_car.jpg", Caption: "Transit and transport: Bike loaded for the journey."},
				{Src: "1fc.jpg", Caption: "First floor commons (1FC) of the Helios Co-op."},
				{Src: "epoch_north_loop.jpg", Caption: "Epoch Coffee, North Loop, Austin. Many hours spent here."},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div> <div class=\"grid md:grid-cols-2 gap-8\"><div><div class=\"flex justify-between items-end mb-4 border-b-2 border-black pb-2\"><h2 class=\"text-xl font-bold uppercase\">Recent Writing</h2><a href=\"/substack\" class=\"hover:underline text-sm\">[View All]</a></div><div class=\"space-y-0 divide-y-2 divide-black border-b-2 border-black\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, post := range data.RecentPosts {
				templ_7745c5c3_Err = components.PostCard(post).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div><div><div class=\"flex justify-between items-end mb-4 border-b-2 border-black pb-2\"><h2 class=\"text-xl font-bold uppercase\">Featured Projects</h2><a href=\"/projects\" class=\"hover:underline text-sm\">[View Gallery]</a></div><div class=\"grid grid-cols-1 gap-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, proj := range data.FeaturedProjects {
				templ_7745c5c3_Err = components.ProjectCard(proj).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base("Home | Alejandro Byrne").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
